### ISSUE TITLE
Env model not training properly for breakout

### ISSUE THREAD

**Issue by mohit291298** [clvoloshin/OPE-tools#4]
I ran your code on breakout after changing Line 328 of file approximate_model.py, it should be 'elif' and not 'if' as mentioned in Issue 1.

When I test the env model trained, it's predicting next image as the previous one always!
I trained on 200 episodes with eps of pi_b=0.5 and epochs as 200, although it stopped_early.

Basically, the results are not reproducible.

Please tell what's the issue??

**Comment by clvoloshin** [comment]
breakout, while indeed is in the code, is actually not something I spent time on for the paper. You are welcome to tinker with it to get it to work but this is beyond the scope of the paper and paper.py.

**Comment by mohit291298** [comment]
Is the MBased approach tested on any visual based domain (complex like enduro, breakout) yet?

**Comment by clvoloshin** [comment]
try enduro

**Comment by clvoloshin** [comment]
To help you out for breakout, my suggestion is to look at whether the NN is outputting all zeros. Recall, that we train the NN on the difference in frames. So if you're seeing the output being the same frame as the last then the NN has probably some relu saturation going on.
